# apiVersion: v1
# kind: Pod
# metadata:
#   name: kaniko
# spec:
#   containers:
#     - name: kaniko
#       image: gcr.io/kaniko-project/executor:latest
#       args: ["--dockerfile=/workspace/dockerfile", "--context=dir://workspace"] # replace with your dockerhub account
#       volumeMounts:
#         - name: kaniko-secret
#           mountPath: /kaniko/.docker
#         - name: dockerfile-storage
#           mountPath: /workspace
#   restartPolicy: Never
#   volumes:
#     - name: kaniko-secret
#       secret:
#         secretName: regcred
#         items:
#           - key: .dockerconfigjson
#             path: config.json
#     - name: dockerfile-storage
#       persistentVolumeClaim:
#         claimName: dockerfile-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udptest
  labels:
    app: udptest
spec:
  replicas: 10
  selector:
    matchLabels:
      app: udptest
  template:
    metadata:
      labels:
        app: udptest
    spec:
      containers:
        - name: udptest
          imagePullPolicy: IfNotPresent
          image: udp-experiment
          ports:
            - containerPort: 3000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: udpservice
spec:
  type: LoadBalancer
  selector:
    app: udptest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: dockerfile
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   hostPath:
#     path: .

# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: dockerfile-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
#   storageClassName: local-storage
